version: '3.7'
services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: example_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 8080:8080