version: '3.7'
services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432

  backend:
    build:
      context: ./backend
    depends_on:
      - database
    ports:
      - "8080:8080"