definitions:
  api.ErrResponse:
    properties:
      errors:
        description: low-level runtime error
        items:
          type: string
        type: array
      status:
        description: user-level status message
        type: string
    type: object
  api.authResponse:
    properties:
      access_token:
        type: string
      user:
        $ref: '#/definitions/api.userResponse'
    type: object
  api.loginRequest:
    properties:
      email:
        default: email@example.com
        type: string
      password:
        default: password
        type: string
    required:
    - email
    - password
    type: object
  api.signupRequest:
    properties:
      email:
        default: email@example.com
        type: string
      password:
        default: password
        type: string
      password_confirmation:
        default: password
        type: string
      username:
        default: username
        type: string
    required:
    - email
    - password
    - password_confirmation
    - username
    type: object
  api.userResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: WebChat golang backend server.
  title: WebChat API
  version: "1.0"
paths:
  /info:
    get:
      consumes:
      - application/json
      description: Get authenticated user's info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.userResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
      security:
      - ApiKeyAuth: []
      summary: Show user info
      tags:
      - users
  /login:
    post:
      consumes:
      - application/json
      description: Send credentials and get JWT
      parameters:
      - description: Credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/api.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.authResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
      summary: Authenticate user and receive JWT
      tags:
      - auth
  /signup:
    post:
      consumes:
      - application/json
      description: Send user data and register new user
      parameters:
      - description: New user data
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/api.signupRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.authResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrResponse'
      summary: Register new user
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
